<template>
  <div id="app">
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate nibh non quam malesuada dictum eget eu odio. Donec pulvinar scelerisque libero, faucibus finibus leo pharetra in. Nunc aliquet vitae sapien vitae placerat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque a justo eu massa commodo efficitur. Integer non arcu id velit pulvinar porttitor. Sed dignissim velit diam, non convallis metus finibus quis. Aliquam viverra augue id nisl venenatis porttitor. Sed et aliquam dolor, non hendrerit quam. Duis fermentum neque eget purus tempus, id pellentesque justo convallis. Mauris vitae lectus volutpat, cursus sem nec, eleifend sem.
      Ut in luctus dui. Aenean at mollis nulla. Fusce eget varius urna. Phasellus id massa eu tortor mattis egestas. Sed eget feugiat purus, sit amet rutrum lectus. Nunc quis ullamcorper ligula, a cursus ipsum. Sed interdum tortor et malesuada elementum. Phasellus vestibulum nec dui in placerat. Nullam lobortis pharetra dictum. Nunc vehicula ligula a eleifend vehicula.
      Vestibulum ante libero, fermentum eu risus nec, tincidunt lobortis nisl. Maecenas semper metus ipsum, at elementum lacus ultricies vitae. Donec vel eros quis urna viverra faucibus. Vivamus vel ante sed mauris pellentesque semper ornare eget nisi. Pellentesque sit amet eros sit amet sapien ullamcorper aliquet ut eu mauris. Donec nisi est, varius at risus non, pulvinar ultricies dui. Etiam velit erat, ultricies in dolor ac, rhoncus tincidunt ipsum. Nam vel pretium purus. Aliquam nec feugiat odio. Quisque libero mauris, finibus at interdum et, mollis vel sapien. Pellentesque sagittis scelerisque lacus non blandit. Nunc lobortis magna eget ante pellentesque, at efficitur mauris molestie. Integer nec tellus vitae turpis vulputate pretium et vitae ligula. Morbi facilisis tincidunt arcu, et mollis neque semper et. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis fermentum at erat nec tristique.
      Aliquam vel enim at nulla iaculis efficitur. Vestibulum rutrum eu odio nec mattis. Duis auctor purus sed lobortis convallis. Cras aliquam urna non justo viverra tincidunt. Ut risus metus, fringilla ut blandit sed, commodo ac dolor. Vestibulum tincidunt purus sit amet est ornare, maximus convallis diam vestibulum. Ut elit nisi, ornare et sodales vel, dapibus eu dolor. Mauris vitae nulla dolor. Sed tincidunt urna a euismod viverra. Nulla facilisi. Ut iaculis sodales risus, in dignissim magna congue et. Mauris id lorem quam. Fusce id arcu varius, aliquet diam sit amet, sollicitudin odio. Ut sed elit odio. Maecenas efficitur consectetur diam ut mattis. Mauris dui est, ornare eget sem sit amet, tristique cursus tortor.
      Mauris consectetur justo non commodo semper. Vestibulum et dignissim orci. Praesent lorem est, iaculis a vulputate non, ullamcorper sed lacus. Nunc pulvinar volutpat dui, eu pharetra quam finibus eu. Duis varius sollicitudin aliquet. Sed accumsan, orci eget faucibus maximus, risus nisl pharetra metus, eget interdum lorem sem quis turpis. Cras malesuada nisl eget ullamcorper dictum. Integer diam velit, tincidunt eget sapien et, vestibulum elementum dui. Maecenas condimentum libero in sagittis posuere. In placerat ipsum eget porttitor elementum.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate nibh non quam malesuada dictum eget eu odio. Donec pulvinar scelerisque libero, faucibus finibus leo pharetra in. Nunc aliquet vitae sapien vitae placerat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque a justo eu massa commodo efficitur. Integer non arcu id velit pulvinar porttitor. Sed dignissim velit diam, non convallis metus finibus quis. Aliquam viverra augue id nisl venenatis porttitor. Sed et aliquam dolor, non hendrerit quam. Duis fermentum neque eget purus tempus, id pellentesque justo convallis. Mauris vitae lectus volutpat, cursus sem nec, eleifend sem.
      Ut in luctus dui. Aenean at mollis nulla. Fusce eget varius urna. Phasellus id massa eu tortor mattis egestas. Sed eget feugiat purus, sit amet rutrum lectus. Nunc quis ullamcorper ligula, a cursus ipsum. Sed interdum tortor et malesuada elementum. Phasellus vestibulum nec dui in placerat. Nullam lobortis pharetra dictum. Nunc vehicula ligula a eleifend vehicula.
      Vestibulum ante libero, fermentum eu risus nec, tincidunt lobortis nisl. Maecenas semper metus ipsum, at elementum lacus ultricies vitae. Donec vel eros quis urna viverra faucibus. Vivamus vel ante sed mauris pellentesque semper ornare eget nisi. Pellentesque sit amet eros sit amet sapien ullamcorper aliquet ut eu mauris. Donec nisi est, varius at risus non, pulvinar ultricies dui. Etiam velit erat, ultricies in dolor ac, rhoncus tincidunt ipsum. Nam vel pretium purus. Aliquam nec feugiat odio. Quisque libero mauris, finibus at interdum et, mollis vel sapien. Pellentesque sagittis scelerisque lacus non blandit. Nunc lobortis magna eget ante pellentesque, at efficitur mauris molestie. Integer nec tellus vitae turpis vulputate pretium et vitae ligula. Morbi facilisis tincidunt arcu, et mollis neque semper et. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis fermentum at erat nec tristique.
      Aliquam vel enim at nulla iaculis efficitur. Vestibulum rutrum eu odio nec mattis. Duis auctor purus sed lobortis convallis. Cras aliquam urna non justo viverra tincidunt. Ut risus metus, fringilla ut blandit sed, commodo ac dolor. Vestibulum tincidunt purus sit amet est ornare, maximus convallis diam vestibulum. Ut elit nisi, ornare et sodales vel, dapibus eu dolor. Mauris vitae nulla dolor. Sed tincidunt urna a euismod viverra. Nulla facilisi. Ut iaculis sodales risus, in dignissim magna congue et. Mauris id lorem quam. Fusce id arcu varius, aliquet diam sit amet, sollicitudin odio. Ut sed elit odio. Maecenas efficitur consectetur diam ut mattis. Mauris dui est, ornare eget sem sit amet, tristique cursus tortor.
      Mauris consectetur justo non commodo semper. Vestibulum et dignissim orci. Praesent lorem est, iaculis a vulputate non, ullamcorper sed lacus. Nunc pulvinar volutpat dui, eu pharetra quam finibus eu. Duis varius sollicitudin aliquet. Sed accumsan, orci eget faucibus maximus, risus nisl pharetra metus, eget interdum lorem sem quis turpis. Cras malesuada nisl eget ullamcorper dictum. Integer diam velit, tincidunt eget sapien et, vestibulum elementum dui. Maecenas condimentum libero in sagittis posuere. In placerat ipsum eget porttitor elementum.
    </p>
    <div class="mt-2 ml-2">
      <button type="button" class="btn btn-primary" @click="open = true">
        Open
      </button>
    </div>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate nibh non quam malesuada dictum eget eu odio. Donec pulvinar scelerisque libero, faucibus finibus leo pharetra in. Nunc aliquet vitae sapien vitae placerat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque a justo eu massa commodo efficitur. Integer non arcu id velit pulvinar porttitor. Sed dignissim velit diam, non convallis metus finibus quis. Aliquam viverra augue id nisl venenatis porttitor. Sed et aliquam dolor, non hendrerit quam. Duis fermentum neque eget purus tempus, id pellentesque justo convallis. Mauris vitae lectus volutpat, cursus sem nec, eleifend sem.
      Ut in luctus dui. Aenean at mollis nulla. Fusce eget varius urna. Phasellus id massa eu tortor mattis egestas. Sed eget feugiat purus, sit amet rutrum lectus. Nunc quis ullamcorper ligula, a cursus ipsum. Sed interdum tortor et malesuada elementum. Phasellus vestibulum nec dui in placerat. Nullam lobortis pharetra dictum. Nunc vehicula ligula a eleifend vehicula.
      Vestibulum ante libero, fermentum eu risus nec, tincidunt lobortis nisl. Maecenas semper metus ipsum, at elementum lacus ultricies vitae. Donec vel eros quis urna viverra faucibus. Vivamus vel ante sed mauris pellentesque semper ornare eget nisi. Pellentesque sit amet eros sit amet sapien ullamcorper aliquet ut eu mauris. Donec nisi est, varius at risus non, pulvinar ultricies dui. Etiam velit erat, ultricies in dolor ac, rhoncus tincidunt ipsum. Nam vel pretium purus. Aliquam nec feugiat odio. Quisque libero mauris, finibus at interdum et, mollis vel sapien. Pellentesque sagittis scelerisque lacus non blandit. Nunc lobortis magna eget ante pellentesque, at efficitur mauris molestie. Integer nec tellus vitae turpis vulputate pretium et vitae ligula. Morbi facilisis tincidunt arcu, et mollis neque semper et. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis fermentum at erat nec tristique.
      Aliquam vel enim at nulla iaculis efficitur. Vestibulum rutrum eu odio nec mattis. Duis auctor purus sed lobortis convallis. Cras aliquam urna non justo viverra tincidunt. Ut risus metus, fringilla ut blandit sed, commodo ac dolor. Vestibulum tincidunt purus sit amet est ornare, maximus convallis diam vestibulum. Ut elit nisi, ornare et sodales vel, dapibus eu dolor. Mauris vitae nulla dolor. Sed tincidunt urna a euismod viverra. Nulla facilisi. Ut iaculis sodales risus, in dignissim magna congue et. Mauris id lorem quam. Fusce id arcu varius, aliquet diam sit amet, sollicitudin odio. Ut sed elit odio. Maecenas efficitur consectetur diam ut mattis. Mauris dui est, ornare eget sem sit amet, tristique cursus tortor.
      Mauris consectetur justo non commodo semper. Vestibulum et dignissim orci. Praesent lorem est, iaculis a vulputate non, ullamcorper sed lacus. Nunc pulvinar volutpat dui, eu pharetra quam finibus eu. Duis varius sollicitudin aliquet. Sed accumsan, orci eget faucibus maximus, risus nisl pharetra metus, eget interdum lorem sem quis turpis. Cras malesuada nisl eget ullamcorper dictum. Integer diam velit, tincidunt eget sapien et, vestibulum elementum dui. Maecenas condimentum libero in sagittis posuere. In placerat ipsum eget porttitor elementum.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate nibh non quam malesuada dictum eget eu odio. Donec pulvinar scelerisque libero, faucibus finibus leo pharetra in. Nunc aliquet vitae sapien vitae placerat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque a justo eu massa commodo efficitur. Integer non arcu id velit pulvinar porttitor. Sed dignissim velit diam, non convallis metus finibus quis. Aliquam viverra augue id nisl venenatis porttitor. Sed et aliquam dolor, non hendrerit quam. Duis fermentum neque eget purus tempus, id pellentesque justo convallis. Mauris vitae lectus volutpat, cursus sem nec, eleifend sem.
      Ut in luctus dui. Aenean at mollis nulla. Fusce eget varius urna. Phasellus id massa eu tortor mattis egestas. Sed eget feugiat purus, sit amet rutrum lectus. Nunc quis ullamcorper ligula, a cursus ipsum. Sed interdum tortor et malesuada elementum. Phasellus vestibulum nec dui in placerat. Nullam lobortis pharetra dictum. Nunc vehicula ligula a eleifend vehicula.
      Vestibulum ante libero, fermentum eu risus nec, tincidunt lobortis nisl. Maecenas semper metus ipsum, at elementum lacus ultricies vitae. Donec vel eros quis urna viverra faucibus. Vivamus vel ante sed mauris pellentesque semper ornare eget nisi. Pellentesque sit amet eros sit amet sapien ullamcorper aliquet ut eu mauris. Donec nisi est, varius at risus non, pulvinar ultricies dui. Etiam velit erat, ultricies in dolor ac, rhoncus tincidunt ipsum. Nam vel pretium purus. Aliquam nec feugiat odio. Quisque libero mauris, finibus at interdum et, mollis vel sapien. Pellentesque sagittis scelerisque lacus non blandit. Nunc lobortis magna eget ante pellentesque, at efficitur mauris molestie. Integer nec tellus vitae turpis vulputate pretium et vitae ligula. Morbi facilisis tincidunt arcu, et mollis neque semper et. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis fermentum at erat nec tristique.
      Aliquam vel enim at nulla iaculis efficitur. Vestibulum rutrum eu odio nec mattis. Duis auctor purus sed lobortis convallis. Cras aliquam urna non justo viverra tincidunt. Ut risus metus, fringilla ut blandit sed, commodo ac dolor. Vestibulum tincidunt purus sit amet est ornare, maximus convallis diam vestibulum. Ut elit nisi, ornare et sodales vel, dapibus eu dolor. Mauris vitae nulla dolor. Sed tincidunt urna a euismod viverra. Nulla facilisi. Ut iaculis sodales risus, in dignissim magna congue et. Mauris id lorem quam. Fusce id arcu varius, aliquet diam sit amet, sollicitudin odio. Ut sed elit odio. Maecenas efficitur consectetur diam ut mattis. Mauris dui est, ornare eget sem sit amet, tristique cursus tortor.
      Mauris consectetur justo non commodo semper. Vestibulum et dignissim orci. Praesent lorem est, iaculis a vulputate non, ullamcorper sed lacus. Nunc pulvinar volutpat dui, eu pharetra quam finibus eu. Duis varius sollicitudin aliquet. Sed accumsan, orci eget faucibus maximus, risus nisl pharetra metus, eget interdum lorem sem quis turpis. Cras malesuada nisl eget ullamcorper dictum. Integer diam velit, tincidunt eget sapien et, vestibulum elementum dui. Maecenas condimentum libero in sagittis posuere. In placerat ipsum eget porttitor elementum.
    </p>

    <app-modal :show="open" @hide="open = false" />
  </div>
</template>

<script>
import AppModal from "@/components/Modal.vue";

export default {
  name: "App",
  components: {
    AppModal,
  },
  data() {
    return {
      open: false,
    };
  },
};
</script>

<style src="bootstrap/dist/css/bootstrap.css"></style>
